version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    build: .
    volumes:
        - .:/usr/app/
        - /usr/app/node_modules
    ports:
        - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    env_file: .env
    

volumes:
  mongodb_data_container:
